added support for wordpress deploy
added wordpress deploy support. (not needed things commented out, will comment better later)

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -68,7 +68,7 @@ abort() {
 #
 
 log() {
-  echo "  ○ $@"
+  echo "  ○○○ $@"
 }
 
 #
@@ -188,7 +188,7 @@ hook() {
 
 setup() {
   local path=`config_get path`
-  log running setup (creating shared/source directories)
+  log running setup -> creating shared/source directories
   run "mkdir -p $path/{shared/{app,web},source}"
   test $? -eq 0 || abort setup paths failed
   log done creating shared/source directories
@@ -300,25 +300,115 @@ symfony() {
 #
 # Setup Wordpress.
 #
+
 wordpress() {
-  local path=`config_get path`
-  local repo=`config_get repo`
-  run "mkdir -p $path/{shared/{web,app},source}"
-  test $? -eq 0 || abort setup paths failed
-  log running setup
+  local path=`config_get path` #get deploy path
+  local repo=`config_get repo` #get repository
+  local broj=`config_get broj` #get number of releases we want to save in source folder
+  local unique=$NOW #get unique name for release folder
+  local ref=$1 #get 
   log cloning $repo
-  run "git clone $repo $path/source"
-  test $? -eq 0 || abort failed to clone
+  run "git clone $repo $path/source/$unique" #cloning repo to unique release folder
+  test $? -eq 0 || abort failed to clone - run deploy prod restore
+  #not needed for wordpress deploy
+  #log downloading composer.phar
+  #run "cd $path/source/$unique && curl -sS https://getcomposer.org/installer | php && php composer.phar install" #download composer.phar to unique release folder
+  #test $? -eq 0 || abort composer not downloaded
+  #log symlinking web/media folder to shared
+  #run "rm -rf $path/source/$unique/web/media" #remove symlink if exists, which it shouldnt
+  #run "ln -sfn $path/shared/web/media $path/source/$unique/web/media" #make symlink to shared folder
+  #test $? -eq 0 || web/media symlink not created
+  #log done
+  #log symlinking .htaccess folder to shared
+  #run "ln -sfn $path/shared/web/.htaccess $path/source/$unique/web/.htaccess" #make symlink to shared folder
+  #test $? -eq 0 || .htaccess symlink not created
+  #log done
+  #log symlinking logs folder to shared
+  #run "rm -rf $path/source/$unique/app/logs" #remove symlink if exists, which it shouldnt
+  #run "ln -sfn $path/shared/app/logs $path/source/$unique/app/logs" #make symlink to shared folder
+  #test $? -eq 0 || logs symlink not created
+  log done
+  log deploying
+  hook pre-deploy || abort pre-deploy hook failed
+  log done running pre-deploy scripts
+  log fetching updates
+  run "cd $path/source/$unique && git fetch --all" #fetch repo into unique release folder
+  test $? -eq 0 || abort fetch failed
+  log done fetching updates
+  # fetch latest tag
+  if test -z "$ref"; then
+    log fetching latest tag
+    ref=`run "cd $path/source/$unique && git for-each-ref refs/tags \
+      --sort=-*authordate \
+      --format='%(refname)' \
+      --count=1 | cut -d '/' -f 3"`
+    test $? -eq 0 || abort failed to determine latest tag
+  fi
+  log done fetching latest tag
+
+  # reset HEAD /mislim da ovo ne treba, da sacuva shared symlinkove
+  #log resetting HEAD to $ref
+  #run "cd $path/source && git reset --hard $ref"
+  #test $? -eq 0 || abort git reset failed
+
+  #log deploys to .deploys file so we can now what has been deployed
+  run "cd $path/source/$unique && \
+      echo \`git rev-parse --short HEAD\` \
+      >> $path/.deploys"
+  test $? -eq 0 || abort deploy log append failed
+  log done logging deploy
+  
+  hook mid-deploy || abort mid-deploy hook failed
+
+  if test $TEST -eq 1; then
+    hook test
+    if test $? -ne 0; then
+      log tests failed, reverting deploy
+      quickly_revert_to 1 && log "revert complete" && exit
+    fi
+  else
+    log ignoring tests
+  fi
+  log done running mid-deploy scripts
   log creating deploy symlinks
-  run "ln -sfn $path/source $path/current"
+  run "ln -sfn $path/source/$unique $path/current" #symlink unique release folder name to current
   test $? -eq 0 || abort symlink failed
-  log removing public_html folder
-  run "rm -rf $path/public_html"
+  log done creating current symlink
   log creating public_html symlink
-  run "ln -sfn $path/current $path/public_html"
+  run "ln -sfn $path/current $path/public_html" #symlink current/web folder to public_html
   test $? -eq 0 || abort public_html symlink failed
-  log setup complete
+  log done symlinking current/web to public_html
+  log removing all but latest $broj deploys
+  run "ls -d -1tr $path/source/* | head -n -$broj | xargs -d '\n' rm -rf" #remove all but $broj number of deploys
+  log done removing all but latest $broj deploys
+  hook post-deploy || abort post-deploy hook failed
+  log done running post-deploy scripts
+  log successfully deployed $ref
 }
+
+
+#
+# Setup Wordpress.
+#
+#wordpresssss() {
+##  local path=`config_get path`
+#  local repo=`config_get repo`
+#  run "mkdir -p $path/{shared/{web,app},source}"
+#  test $? -eq 0 || abort setup paths failed
+#  log running setup
+#  log cloning $repo
+#  run "git clone $repo $path/source"
+#  test $? -eq 0 || abort failed to clone
+#  log creating deploy symlinks
+#  run "ln -sfn $path/source $path/current"
+#  test $? -eq 0 || abort symlink failed
+#  log removing public_html folder
+#  run "rm -rf $path/public_html"
+#  log creating public_html symlink
+#  run "ln -sfn $path/current $path/public_html"
+#  test $? -eq 0 || abort public_html symlink failed
+#  log setup complete
+#}
 
 #
 # Reset user account to defaults.
