added date for release in source dir

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -6,9 +6,9 @@
 #
 # https://github.com/visionmedia/deploy
 #
-set -e
-​
-DIST=dist_`date +%s | sha256sum | head -c 12`
+
+DIST="date +%s | sha256sum | head -c 12"
+NOW=$(date +"%Y-%m-%d-%S")
 VERSION="0.6.0"
 CONFIG=./deploy.conf
 LOG=/tmp/deploy.log
@@ -188,11 +188,12 @@ hook() {
 setup() {
   local path=`config_get path`
   local repo=`config_get repo`
+  #local unique=$NOW
   run "mkdir -p $path/{shared/{logs,pids},source}"
   test $? -eq 0 || abort setup paths failed
   log running setup
   log cloning $repo
-  run "git clone $repo $path/source"
+  run "git clone $repo $path/source/$unique"
   test $? -eq 0 || abort failed to clone
   run "ln -sfn $path/source $path/current"
   test $? -eq 0 || abort symlink failed
@@ -205,36 +206,84 @@ setup() {
 symfony() {
   local path=`config_get path`
   local repo=`config_get repo`
+  local unique=$NOW
   run "mkdir -p $path/{shared/{web,app},source}"
   test $? -eq 0 || abort setup paths failed
   log running setup
   log cloning $repo
-  run "git clone $repo $path/source"
+  run "git clone $repo $path/source/$unique"
   test $? -eq 0 || abort failed to clone - run deploy prod restore
-  log creating deploy symlinks
-  run "ln -sfn $path/source $path/current"
-  test $? -eq 0 || abort symlink failed
+  log downloading composer.phar
+  run "cd $path/source/$unique && curl -sS https://getcomposer.org/installer | php"
+  test $? -eq 0 || abort composer not downloaded
+  log symlinking web/media folder to shared
+  run "mkdir $path/shared/web/media && rm -rf $path/source/$unique/web/media"
+  run "ln -sfn $path/shared/web/media $path/source/$unique/web/media"
+  test $? -eq 0 || web/media symlink not created
+  log symlinking .htaccess folder to shared
+  run "touch $path/shared/web/.htaccess"
+  run "ln -sfn $path/shared/web/.htaccess $path/source/$unique/web/.htaccess"
+  test $? -eq 0 || .htaccess symlink not created
+  log symlinking logs folder to shared
+  run "mkdir $path/shared/app/logs && rm -rf $path/source/$unique/app/logs"
+  run "ln -sfn $path/shared/app/logs $path/source/$unique/app/logs"
+  test $? -eq 0 || logs symlink not created
+  log deploying
+
+  hook pre-deploy || abort pre-deploy hook failed
+
+  # fetch source
+  log fetching updates
+  run "cd $path/source/$unique && git fetch --all"
+  test $? -eq 0 || abort fetch failed
+
+  # latest tag
+  if test -z "$ref"; then
+    log fetching latest tag
+    ref=`run "cd $path/source/$unique && git for-each-ref refs/tags \
+      --sort=-*authordate \
+      --format='%(refname)' \
+      --count=1 | cut -d '/' -f 3"`
+    test $? -eq 0 || abort failed to determine latest tag
+  fi
+
+  # reset HEAD /mislim da ovo ne treba, da sacuva shared symlinkove
+  #log resetting HEAD to $ref
+  #run "cd $path/source && git reset --hard $ref"
+  #test $? -eq 0 || abort git reset failed
+
+  # deploy log
+  run "cd $path/source/$unique && \
+      echo \`git rev-parse --short HEAD\` \
+      >> $path/.deploys"
+  test $? -eq 0 || abort deploy log append failed
+
+  # link current
+  #run "ln -sfn $path/source/$unique $path/current"
+  #test $? -eq 0 || abort symlink failed
   log removing public_html folder
   run "rm -rf $path/public_html"
   log creating public_html symlink
   run "ln -sfn $path/current/web $path/public_html"
   test $? -eq 0 || abort public_html symlink failed
-  log downloading composer.phar
-  run "cd $path/source && curl -sS https://getcomposer.org/installer | php"
-  test $? -eq 0 || abort composer not downloaded
-  log symlinking web/media folder to shared
-  run "mkdir $path/shared/web/media"
-  run "ln -sfn $path/shared/web/media $path/source/web"
-  test $? -eq 0 || web/media symlink not created
-  log symlinking .htaccess folder to shared
-  run "touch $path/shared/web/.htaccess"
-  run "ln -sfn $path/shared/web/.htaccess $path/source/web/.htaccess"
-  test $? -eq 0 || .htaccess symlink not created
-  log symlinking logs folder to shared
-  run "mkdir $path/shared/app/logs && rm -rf $path/source/app/logs"
-  run "ln -sfn $path/shared/app/logs $path/source/app/logs"
-  test $? -eq 0 || logs symlink not created
-  log setup complete
+  log creating deploy symlinks
+  run "ln -sfn $path/source/$unique $path/current"
+  test $? -eq 0 || abort symlink failed
+
+  hook post-deploy || abort post-deploy hook failed
+
+  if test $TEST -eq 1; then
+    hook test
+    if test $? -ne 0; then
+      log tests failed, reverting deploy
+      quickly_revert_to 1 && log "revert complete" && exit
+    fi
+  else
+    log ignoring tests
+  fi
+
+  # done
+  log successfully deployed $ref
 }
 #curl -sS https://getcomposer.org/installer | php
 #
