added 3 symfony versions

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -9,7 +9,7 @@
 
 NOW=$(date +"%d-%m-%Y-%H-%M-%S")
 NUMBER=$(ls -l | grep ^d | wc -l)
-VERSION="1.0.24"
+VERSION="1.1.0"
 HOME="$HOME/"
 CONFIG=./deploy.conf
 LOG=/tmp/deploy.log
@@ -37,7 +37,8 @@ usage() {
   Commands:
 
     setup                run remote setup commands
-    symfony              run remote symfony deploy commands
+    symfony2             run remote symfony deploy commands
+    symfony3             run remote symfony deploy commands
     symfony4             run remote symfony4 deploy commands
     node                 run remote node deploy commands
     presta               run remote prestashop deploy commands
@@ -251,9 +252,9 @@ setup() {
 }
 
 #
-# Deploy Symfony.
+# Deploy Symfony2.
 #
-symfony() {
+symfony2() {
   local path=`config_get path` #get deploy path
   local repo=`config_get repo` #get repository
   local branch=`config_get ref` #get branch name
@@ -355,6 +356,118 @@ symfony() {
   #log creating var/logs symlink
   #run "rm -rf $path/source/$unique/var/logs && ln -sfn $path/shared/var/logs/ $path/source/$unique/var/logs" #symlink current/web folder to public_html
   #test $? -eq 0 || abort var/logs symlink failed
+  log removing all but latest $broj deploys
+  run "ls -d -1tr $path/source/* | head -n -$broj | xargs -d '\n' rm -rf" #remove all but $broj number of deploys
+  log done removing all but latest $broj deploys
+  hook post-deploy || abort post-deploy hook failed
+  log done running post-deploy scripts
+  log successfully deployed $ref
+}
+
+#
+# Deploy Symfony3.
+#
+symfony3() {
+  local path=`config_get path` #get deploy path
+  local repo=`config_get repo` #get repository
+  local branch=`config_get ref` #get branch name
+  local php_path=`config_get php_path` #get php path to use
+  local action=`config_get comp` #get composer action (install or update)
+  local broj=`config_get broj` #get number of releases we want to save in source folder
+  local unique=$NOW #get unique name for release folder
+  log cloning $repo
+  run "git clone $repo -b $branch $path/source/$unique" #cloning repo to unique release folder
+  test $? -eq 0 || abort failed to clone - run deploy prod restore
+  #log removing parameters.yml symlink
+  #run "rm -f $path/shared/app/config/parameters.yml"
+  #test $? -eq 0 || parameters.yml symlink not removed
+  log symlinking parameters.yml file to shared
+  run "ln -sfn $path/shared/app/config/parameters.yml $path/source/$unique/app/config/parameters.yml" #make symlink to shared folder
+  test $? -eq 0 || .htaccess symlink not created
+  log done
+  log downloading composer.phar
+  run "cd $path/source/$unique && curl -sS https://getcomposer.org/installer | php && $php_path composer.phar $action" #download composer.phar to unique release folder
+  test $? -eq 0 || abort composer not downloaded or composer $action not executed
+  log done
+  log symlinking web/media folder to shared
+  run "rm -rf $path/source/$unique/web/media" #remove symlink if exists, which it shouldnt
+  run "ln -sfn $path/shared/web/media $path/source/$unique/web/media" #make symlink to shared folder
+  test $? -eq 0 || web/media symlink not created
+  log done
+  log symlinking .htaccess folder to shared
+  run "ln -sfn $path/shared/web/.htaccess $path/source/$unique/web/.htaccess" #make symlink to shared folder
+  test $? -eq 0 || .htaccess symlink not created
+  log done  
+  log symlinking logs folder to shared
+  run "rm -rf $path/source/$unique/app/logs" #remove symlink if exists, which it shouldnt
+  run "ln -sfn $path/shared/app/logs $path/source/$unique/app/logs" #make symlink to shared folder
+  test $? -eq 0 || logs symlink not created
+  log done
+  log change hook permissions
+  run "chmod -R 755 $path/source/$unique" #changing permissions so that hook scripts can run
+  test $? -eq 0 || abort failed to change permissions
+  log done
+  log deploying
+  hook pre-deploy || abort pre-deploy hook failed
+  log done running pre-deploy scripts
+  log fetching updates
+  run "cd $path/source/$unique && git fetch --all" #fetch repo into unique release folder
+  test $? -eq 0 || abort fetch failed
+  log done fetching updates
+  # fetch latest tag
+  if test -z "$ref"; then
+    log fetching latest tag
+    ref=`run "cd $path/source/$unique && git for-each-ref refs/tags \
+      --sort=-*authordate \
+      --format='%(refname)' \
+      --count=1 | cut -d '/' -f 3"`
+    test $? -eq 0 || abort failed to determine latest tag
+  fi
+  log done fetching latest tag
+  local ref=$(git rev-parse --short HEAD) #get latest commit HEAD  
+  # reset HEAD /mislim da ovo ne treba, da sacuva shared symlinkove
+  #log resetting HEAD to $ref
+  #run "cd $path/source && git reset --hard $ref"
+  #test $? -eq 0 || abort git reset failed
+
+  #log deploys to .deploys file so we can now what has been deployed
+  run "cd $path/source/$unique && \
+      echo \`git rev-parse --short HEAD\` \
+      >> $path/.deploys"
+  test $? -eq 0 || abort deploy log append failed
+  log done logging deploy
+  
+  hook mid-deploy || abort mid-deploy hook failed
+
+  if test $TEST -eq 1; then
+    hook test
+    if test $? -ne 0; then
+      log tests failed, reverting deploy
+      quickly_revert_to 1 && log "revert complete" && exit
+    fi
+  else
+    log ignoring tests
+  fi
+  log done running mid-deploy scripts
+  log removing app_*.php files
+  run "rm -rf $path/source/$unique/web/app_*.php" #remove app_dev.php file on deploy
+  test $? -eq 0 || abort app_*.php removal failed
+  log done removing app_*.php files
+  log creating deploy symlinks
+  run "ln -sfn $path/source/$unique $path/current" #symlink unique release folder name to current
+  test $? -eq 0 || abort symlink failed
+  log done creating current symlink #nakon ovoga ide rm -rf public_html i symlink
+  log deleting public_html folder
+  run "rm -rf $path/public_html"
+  test $? -eq 0 || public_html not deleted
+  log done
+  log creating public_html symlink
+  run "rm -rf $path/public_html && ln -sfn $path/current/web $path/public_html" #symlink current/web folder to public_html
+  test $? -eq 0 || abort public_html symlink failed
+  log done symlinking current/web to public_html
+  log creating var/logs symlink
+  run "rm -rf $path/source/$unique/var/logs && ln -sfn $path/shared/var/logs/ $path/source/$unique/var/logs" #symlink current/web folder to public_html
+  test $? -eq 0 || abort var/logs symlink failed
   log removing all but latest $broj deploys
   run "ls -d -1tr $path/source/* | head -n -$broj | xargs -d '\n' rm -rf" #remove all but $broj number of deploys
   log done removing all but latest $broj deploys
@@ -1082,7 +1195,8 @@ while test $# -ne 0; do
     prev|previous) require_env; nth_deploy_commit 2; exit ;;
     revert) require_env; revert_to ${1-1}; exit ;;
     setup) require_env; setup $@; exit ;;
-    symfony) require_env; symfony $@; exit ;;
+    symfony2) require_env; symfony $@; exit ;;
+    symfony3) require_env; symfony $@; exit ;;
     symfony4) require_env; symfony4 $@; exit ;;
     drupal) require_env; drupal $@; exit ;;
     presta) require_env; presta $@; exit ;;
