various fixes
fixes for atomic deploys

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -7,7 +7,7 @@
 # https://github.com/visionmedia/deploy
 #
 
-NOW=$(date +"%d-%m-%Y-%k-%M-%S")
+NOW=$(date +"%d-%m-%Y-%H-%M-%S")
 NUMBER=$(ls -l | grep ^d | wc -l)
 VERSION="0.6.0"
 CONFIG=./deploy.conf
@@ -169,9 +169,10 @@ hook() {
   local hook=$1
   local path=`config_get path`
   local cmd=`config_get $hook`
+  local unique=$NOW
   if test -n "$cmd"; then
     log "executing $hook \`$cmd\`"
-    run "cd $path/current; \
+    run "cd $path/source/$unique; \
       SHARED=\"$path/shared\" \
       $cmd 2>&1 | tee -a $LOG; \
       exit \${PIPESTATUS[0]}"
@@ -192,9 +193,9 @@ setup() {
   run "mkdir -p $path/{shared/{logs,pids},source}"
   test $? -eq 0 || abort setup paths failed
   log running setup
-  log cloning $repo
-  run "git clone $repo $path/source/$unique"
-  test $? -eq 0 || abort failed to clone
+  #log cloning $repo
+  #run "git clone $repo $path/source/$unique"
+  #test $? -eq 0 || abort failed to clone
   run "ln -sfn $path/source $path/current"
   test $? -eq 0 || abort symlink failed
   log setup complete
@@ -260,10 +261,10 @@ symfony() {
   test $? -eq 0 || abort deploy log append failed
 
   # link current
-  run "ln -sfn $path/source/$unique $path/current"
-  test $? -eq 0 || abort symlink failed
+  #run "ln -sfn $path/source/$unique $path/current"
+  #test $? -eq 0 || abort symlink failed
   
-  hook post-deploy || abort post-deploy hook failed
+  hook mid-deploy || abort mid-deploy hook failed
 
   if test $TEST -eq 1; then
     hook test
@@ -274,20 +275,23 @@ symfony() {
   else
     log ignoring tests
   fi
-
-  # done
-  log successfully deployed $ref
+ 
   #log removing public_html folder
   #run "rm -rf $path/public_html"
-  #log creating deploy symlinks
-  #run "ln -sfn $path/source/$unique $path/current"
-  #test $? -eq 0 || abort symlink failed
+  log creating deploy symlinks
+  run "ln -sfn $path/source/$unique $path/current"
+  test $? -eq 0 || abort symlink failed
   log creating public_html symlink
   run "ln -sfn $path/current/web $path/public_html"
   test $? -eq 0 || abort public_html symlink failed
+  log removing all but latest $broj deploys
   run "ls -d -1tr $path/source/* | head -n -$broj | xargs -d '\n' rm -rf"
+   # done
+  hook post-deploy || abort post-deploy hook failed
+  log successfully deployed $ref
+
 }
-#curl -sS https://getcomposer.org/installer | php
+
 #
 # Setup Wordpress.
 #
